DROP DATABASE IF EXISTS BILLMANAGER;
CREATE DATABASE BILLMANAGER;
USE BILLMANAGER;

CREATE TABLE USUARIOS (
	USU_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USU_NOME VARCHAR(100),
    USU_EMAIL VARCHAR(100),
    USU_SENHA VARCHAR(100)
);

CREATE TABLE CONTAS (
    CON_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    CON_NOME VARCHAR(100),
    CON_VALOR DOUBLE(6,2),
    CON_DATAVENC DATE,
    CON_PAGO ENUM('SIM', 'NAO'),
    FK_USUARIOS_USU_ID INTEGER
);
 
ALTER TABLE CONTAS ADD CONSTRAINT FK_CONTAS_2
    FOREIGN KEY (FK_USUARIOS_USU_ID)
    REFERENCES USUARIOS (USU_ID)
    ON DELETE RESTRICT;